import type { ShiftRecord } from './scoring';

export const SIMULATED_SHIFTS: ShiftRecord[] = [
  {
    id: 'S-101',
    operatorId: 'OP-4092',
    operatorName: 'Marcus Vance',
    shiftDate: '2026-09-23',
    durationHrs: 8,
    equipmentId: 'EXC-842',
    operationType: 'Excavation',
    safetyViolations: 0,
    safetyNearMisses: 1,
    readinessAvg: 93,
    fuelConsumedLiters: 165,
    expectedFuelLiters: 160,
    idleTimeRatio: 0.12,
    completedCycles: 110,
    actualCycleTimeAvg: 4.2,
    targetCycleTime: 4.5,
  },
  {
    id: 'S-102',
    operatorId: 'OP-4105',
    operatorName: 'Elena Rostova',
    shiftDate: '2026-09-23',
    durationHrs: 8,
    equipmentId: 'EXC-843',
    operationType: 'Excavation',
    safetyViolations: 0,
    safetyNearMisses: 0,
    readinessAvg: 96,
    fuelConsumedLiters: 155,
    expectedFuelLiters: 160,
    idleTimeRatio: 0.10,
    completedCycles: 115,
    actualCycleTimeAvg: 4.0,
    targetCycleTime: 4.5,
  },
  {
    id: 'S-103',
    operatorId: 'OP-3881',
    operatorName: 'James Holden',
    shiftDate: '2026-09-23',
    durationHrs: 8,
    equipmentId: 'EXC-845',
    operationType: 'Excavation',
    safetyViolations: 1, // Will cap velocity and penalize safety
    safetyNearMisses: 2,
    readinessAvg: 85,
    fuelConsumedLiters: 175,
    expectedFuelLiters: 160,
    idleTimeRatio: 0.18,
    completedCycles: 125, // Very fast but unsafe
    actualCycleTimeAvg: 3.6,
    targetCycleTime: 4.5,
  },
  {
    id: 'S-104',
    operatorId: 'OP-4122',
    operatorName: 'Sarah Chen',
    shiftDate: '2026-09-23',
    durationHrs: 4, // Shorter shift but valid
    equipmentId: 'EXC-848',
    operationType: 'Excavation',
    safetyViolations: 0,
    safetyNearMisses: 0,
    readinessAvg: 98,
    fuelConsumedLiters: 80,
    expectedFuelLiters: 80,
    idleTimeRatio: 0.08,
    completedCycles: 55,
    actualCycleTimeAvg: 4.3,
    targetCycleTime: 4.5,
  },
  {
    id: 'S-105',
    operatorId: 'OP-4200',
    operatorName: 'David Kim',
    shiftDate: '2026-09-23',
    durationHrs: 8,
    equipmentId: 'EXC-850',
    operationType: 'Excavation',
    safetyViolations: 0,
    safetyNearMisses: 0,
    readinessAvg: 89,
    fuelConsumedLiters: 190, // High fuel usage
    expectedFuelLiters: 160,
    idleTimeRatio: 0.35, // High idle penalty
    completedCycles: 90, // Slower cycles
    actualCycleTimeAvg: 5.2,
    targetCycleTime: 4.5,
  },
  {
    id: 'S-106',
    operatorId: 'OP-4201',
    operatorName: 'New Hire (In Training)',
    shiftDate: '2026-09-23',
    durationHrs: 0.5, // Insufficient Data
    equipmentId: 'EXC-860',
    operationType: 'Excavation',
    safetyViolations: 0,
    safetyNearMisses: 0,
    readinessAvg: 90,
    fuelConsumedLiters: 15,
    expectedFuelLiters: 10,
    idleTimeRatio: 0.10,
    completedCycles: 1, // Insufficient
    actualCycleTimeAvg: 6.0,
    targetCycleTime: 4.5,
  }
];
